### PR TITLE
feat: add solo smoke test to test flow

### LINKED ISSUE #876: Consolidate smoke test of smart contract and javascript sdk with solo
### Feature to Enhance

```markdown
Clone required example or unit test at solo repo
so we can run end to end and integrated test without
dependencies on other repos
```

### Requested Enhancement

Duplicated some example tests at solo repo

### Business Need

N/A

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* Added a flag `generateEcdsaKey ` so user can use `solo account create` to create account with auto generated ECDSA key, no need to provide a EDCSA key string to solo
* Added a flag `createAmount` so solo can continuously generating many account, so we can use the feature to generate background transactions when testing relay node.  Cannot use original standalone `solo account create` since it is too slow can only finish one account in about 9~10 seconds
* Retrieve and display EVM address for user with `solo account get` command

### Related Issues

* Closes #876

### CODE REVIEW

**Review by jeromy-cannon — APPROVED** [review]

**Review by jeromy-cannon — CHANGES_REQUESTED** [review]
error handling needs to be fixed in the script.  You have a test case error, but it ate the error and showed a success: https://github.com/hashgraph/solo/actions/runs/12238568891/job/34136963069?pr=905#step:9:518

**Comment by JeffreyDallas** [comment]
> error handling needs to be fixed in the script. You have a test case error, but it ate the error and showed a success: https://github.com/hashgraph/solo/actions/runs/12238568891/job/34136963069?pr=905#step:9:518

This is the issue I mentioned before that with linux github runner,
port-forward randomly stop itself without any errors or logs,
so I wrapped the test within a retry function, try five times.

also there is a background thread kept re-enable port-forward.

from log you can see results of `ps -ef |grep port-forwar`
the relay node port forward no longer there,
after renabled and retry the test, test would pass

```
/home/runner/_work/solo
-----------------------
runner      1522       1  0 15:18 ?        00:00:00 kubectl port-forward -n solo-e2e svc/haproxy-node1-svc 50211:50211
runner      1725       1  0 15:19 ?        00:00:00 kubectl port-forward -n solo-e2e svc/hedera-explorer 8080:80
runner      1729       1  0 15:19 ?        00:00:00 kubectl port-forward svc/mirror-grpc -n solo-e2e 5600:5600
runner      3096    2692  0 15:22 ?        00:00:00 grep port-forward
Enable port forward round 5
runner      1522       1  0 15:18 ?        00:00:00 kubectl port-forward -n solo-e2e svc/haproxy-node1-svc 50211:50211
runner      1725       1  0 15:19 ?        00:00:00 kubectl port-forward -n solo-e2e svc/hedera-explorer 8080:80
runner      1729       1  0 15:19 ?        00:00:00 kubectl port-forward svc/mirror-grpc -n solo-e2e 5600:5600
runner      3099    2692  3 15:22 ?        00:00:00 kubectl port-forward -n solo-e2e svc/relay-node1-hedera-json-rpc-relay 7[546](https://github.com/hashgraph/solo/actions/runs/12238568891/job/34136963069?pr=905#step:9:547):7546
runner      3190    2692  0 15:22 ?        00:00:00 grep port-forward
```

**Comment by JeffreyDallas** [comment]
This is the same issue repeated on macOS


line 285 we can see all port forwards are still active
after a few seconds, test failed,
line 332 show relay port forward is gone.

[smoke_test_log.txt](https://github.com/user-attachments/files/18085276/smoke_test_log.txt)

**Review by mishomihov00 — DISMISSED** [review]
Review applies to:
`.github/workflows/flow-task-test.yaml`

**Comment by jeromy-cannon** [comment]
My point, is that the workflow should be showing a failure, but it is showing a success.

**Comment by JeffreyDallas** [comment]
> My point, is that the workflow should be showing a failure, but it is showing a success.

What shown in the log is first try of test is failed due to port-forward is stopped, 
but after re-enable port-forward, test itself is passed.

The workflow is passed because test success with the retry less than 5 times.

**Comment by JeffreyDallas** [comment]
After some experiment from last night, I found if port-forward were called within Task,
they might randomly stopped.

but if port-forward were called outside Task, they would be consistently working.

I did not have an explanation for this.
But did find a workaround in test script:
1) kill port-forward first to remove those Task command enabled port forward
2) restart port-foward within test script

**Review by jeromy-cannon — APPROVED** [review]

**Comment by jeromy-cannon** [comment]
that makes sense, thank you for the explanation, approved

**Pull request merged**
